# Generated by Django 4.0.5 on 2022-06-23 16:26

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('sexo', models.CharField(blank=True, max_length=2)),
                ('email', models.EmailField(blank=True, max_length=50, unique=True, verbose_name='correo electronico')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='AdministradorModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='AplicaciónModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('correo', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'aplicación',
            },
        ),
        migrations.CreateModel(
            name='ConsultaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='media/default.jpg', upload_to=api.models.upload_to, verbose_name='Imagen')),
                ('estado', models.PositiveIntegerField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consulta',
            },
        ),
        migrations.CreateModel(
            name='RespondeModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=250, unique=True)),
                ('consulta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consultamodelo')),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'responde',
            },
        ),
        migrations.CreateModel(
            name='PagosModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('costo', models.FloatField()),
                ('aplicacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aplicaciónmodelo')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='FacturaModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.FloatField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(max_length=250)),
                ('consulta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consultamodelo')),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pago_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pagosmodelo')),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='EnfermedadModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(default='media/default.jpg', upload_to=api.models.upload_toEnfermedad, verbose_name='Imagen')),
                ('cant_imagen', models.PositiveIntegerField()),
                ('tratamiento', models.TextField(max_length=250)),
                ('aplicacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.aplicaciónmodelo')),
            ],
            options={
                'db_table': 'enfermedad',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField()),
                ('imagen', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('consulta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consultamodelo')),
                ('enfermedad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enfermedadmodelo')),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diagnostico',
            },
        ),
    ]
